version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: testapp
      MYSQL_PASSWORD: testapp
      MYSQL_DATABASE: testapp
    volumes:
      - ./db:/var/lib/mysql
