---
pkgs: [
            'python3', 'python3-dev', 'python3-pip', 'git', 'mysql-server','mysql-common',
            'python-pymysql', 'python3-pymysql', 'nginx'
    ]
repo: https://github.com/ramazeska/ormuco.git
repo_vers: master
clone_path: /opt/ormuco
num_workers: 2
sqluser: testapp
sqlpassword: testapp
dbname: testapp
mysql_root_password: secret
cert_path: /etc/ssl/private