---
- name: Create webapp instance
  ec2:
    count: "{{ num_instance }}"
    group_id: "{{ group_id }}"
    image: "{{ ami }}"
    instance_type: t2.micro
    state: present
    vpc_subnet_id: "{{ vpc_subnet }}"
    wait: yes
    region: "{{ region }}"
    assign_public_ip: yes
    instance_tags: {"type": "webapp"}
    count_tag:
      type: webapp

    key_name: "{{ key_name }}"
  register: ec2
- name: add instance to hostgroup
  add_host:
    hostname: "{{ item.public_dns_name }}"
    ansible_user: ubuntu
    ansible_ssh_host: "{{item.public_ip}}"
    ansible_ssh_private_key_file: "{{private_key}}"
    dnsname: "{{ item.public_dns_name }}"
    groupname: launched
  loop: "{{ ec2.instances }}"
- name: Wait for SSH to come up
  delegate_to: "{{ item.public_dns_name }}"
  wait_for_connection:
    delay: 60
    timeout: 320
  loop: "{{ ec2.instances }}"
